#include <iostream>
#include <list>
#include <string>
#include <iterator>
#include <vector>
#include <memory>
#include <map>
using std::cout;
using std::endl;
using std::iterator;
using std::list;
using std::map;
using std::shared_ptr;
using std::string;
using std::unique_ptr;
using std::vector;
using std::weak_ptr;
